name: release and deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        rm -rf ./node_modules/chromedriver
        rm -rf ./node_modules/geckodriver
        cp -r ./lib/* ./node_modules
        npm test
